#ifndef TOWERDEFENSE_VIEWCONSTANTS_H
#define TOWERDEFENSE_VIEWCONSTANTS_H

#define TOWER_BUTTON_WIDTH 102
#define TOWER_BUTTON_HEIGHT 102
#define SPELL_BUTTON_WIDTH 50
#define SPELL_BUTTON_HEIGHT 50
#define PADDING_HUD 2

#define ELEMENTAL_EARTH 0
#define ELEMENTAL_FIRE 1
#define ELEMENTAL_WATER 2
#define ELEMENTAL_AIR 3

#define CMD_EARTH_TOWER 0

#define CMD_FIRE_TOWER 1
#define CMD_WATER_TOWER 2
#define CMD_AIR_TOWER 3

#define CMD_TERRAFORMING 4
#define CMD_GRIETA 5
#define CMD_FIREWALL 6
#define CMD_METEORITO 7
#define CMD_CONGELACION 8
#define CMD_VENTISCA 9
#define CMD_TORNADO 10
#define CMD_RAYO 11

#endif //TOWERDEFENSE_VIEWCONSTANTS_H
