#ifndef TOWERDEFENSE_VIEWCONSTANTS_H
#define TOWERDEFENSE_VIEWCONSTANTS_H

#define HUD_ICON_SIZE 47
#define HUD_BUTTON_X 61
#define HUD_BUTTON_Y 73

#define MARQUESINA_W 150
#define MARQUESINA_H 17
#define MARQUESINA_OFFSET_X 13

#define EXIT_BUTTON_SIZE 48
#define PADDING_HUD 2

#define ELEMENTAL_EARTH 0
#define ELEMENTAL_FIRE 1
#define ELEMENTAL_WATER 2
#define ELEMENTAL_AIR 3

#define CMD_EARTH_TOWER 0
#define CMD_FIRE_TOWER 1
#define CMD_WATER_TOWER 2
#define CMD_AIR_TOWER 3

#define CMD_TERRAFORMING 4
#define CMD_GRIETA 5
#define CMD_FIREWALL 6
#define CMD_METEORITO 7
#define CMD_CONGELACION 8
#define CMD_VENTISCA 9
#define CMD_TORNADO 10
#define CMD_RAYO 11

#define CMD_PING 12

#define CMD_DAMAGE 13
#define CMD_RANGE 14
#define CMD_IMPACT 15
#define CMD_FREEZE 16

#define CMD_EXIT -2

#endif //TOWERDEFENSE_VIEWCONSTANTS_H
