#ifndef TOWERDEFENSE_VIEWCONSTANTS_H
#define TOWERDEFENSE_VIEWCONSTANTS_H

#define TOWER_BUTTON_WIDTH 100
#define TOWER_BUTTON_HEIGHT 100
#define FIRE_TOWER_KEY "FIRE"
#define WATER_TOWER_KEY "WATER"
#define EARTH_TOWER_KEY "EARTH"
#define AIR_TOWER_KEY "AIR"

#endif //TOWERDEFENSE_VIEWCONSTANTS_H
