#ifndef TOWERDEFENSE_CONSTANTS_H
#define TOWERDEFENSE_CONSTANTS_H

#define SUPERFICIE_BUTTON_WIDTH 100
#define SUPERFICIE_BUTTON_HEIGHT 100

#define AGREGAR_CAMINO_BUTTON_X 0
#define AGREGAR_CAMINO_BUTTON_Y 100
#define AGREGAR_CAMINO_BUTTON_WIDTH 100
#define AGREGAR_CAMINO_BUTTON_HEIGHT 100

#define AGREGAR_TIERRA_BUTTON_X 100
#define AGREGAR_TIERRA_BUTTON_Y 100
#define AGREGAR_TIERRA_BUTTON_WIDTH 100
#define AGREGAR_TIERRA_BUTTON_HEIGHT 100

#define AGREGAR_PORTAL_ENTRADA_BUTTON_X 200
#define AGREGAR_PORTAL_ENTRADA_BUTTON_Y 100
#define AGREGAR_PORTAL_ENTRADA_BUTTON_WIDTH 100
#define AGREGAR_PORTAL_ENTRADA_BUTTON_HEIGHT 100

#define NUEVA_HORDA_BUTTON_X 0
#define NUEVA_HORDA_BUTTON_Y 200
#define NUEVA_HORDA_BUTTON_WIDTH 200
#define NUEVA_HORDA_BUTTON_HEIGHT 50

#define TOTAL_MAIN_BUTTONS 9

#define HORDA_ENEMIGO_PADDING 275
#define HORDA_ENEMIGO_IMG_SIZE 50
#define HORDA_MODIFY_QUANTITY_PADDING HORDA_ENEMIGO_PADDING + HORDA_ENEMIGO_IMG_SIZE
#define HORDA_MODIFY_QUANTITY_SIZE 25
#define HORDA_TOTAL_HEIGHT 100
#define HORDA_QUANTITY_WIDTH 50
#define HORDA_QUANTITY_HEIGHT 28
#define HORDA_QUANTITY_PADDING HORDA_MODIFY_QUANTITY_PADDING + HORDA_MODIFY_QUANTITY_SIZE
#define HORDA_TOTAL_ENEMIES 6
#define HORDA_BUTTONS_PER_ENEMY 4
#define HORDA_TOTAL_BUTTONS HORDA_BUTTONS_PER_ENEMY * (HORDA_TOTAL_ENEMIES + 1)
 //El 1 es por los botones de tiempo

#define ABMONIBLE_KEY "abmonible"
#define ESPECTRO_KEY "espectro"
#define DEMONIO_VERDE_KEY "demonio_verde"
#define HALCON_SANGRIENTO_KEY "halcon_sangriento"
#define NO_MUERTO_KEY "no_muerto_key"
#define HOMBRE_CABRA_KEY "hombre_cabra"

#endif //TOWERDEFENSE_CONSTANTS_H
