unit_base_step_delay_ms: 3000
towers:
 ground:
  range: 4
  cooldown_sec: 1
  damage: 20
  upgrade_range_increase: 2
  upgrade_range_mult: 500
  upgrade_range_base: 2
  upgrade_damage_increase: 10
  upgrade_damage_mult: 100
  upgrade_damage_base: 1.5
 fire:
  range: 4
  cooldown_sec: 4
  target_damage: 20
  collateral_damage: 3
  collateral_range: 1
  upgrade_range_increase: 1
  upgrade_range_mult: 100
  upgrade_range_base: 2
  upgrade_damage_increase: 6
  upgrade_collateral_damage_increase: 3
  upgrade_damage_base: 1.5
  upgrade_damage_mult: 100
  upgrade_collateral_range_increase: 1
  upgrade_collateral_range_base: 2
  upgrade_collateral_range_mult: 500
 water:
  range: 4
  cooldown_sec: 4
  damage: 20
  slow_percent: 25
  slow_duration_sec: 2
  upgrade_range_increase: 1
  upgrade_range_mult: 100
  upgrade_range_base: 2
  upgrade_damage_increase: 4
  upgrade_damage_mult: 100
  upgrade_damage_base: 1.5
  upgrade_slow_percent_increase: 25
  upgrade_slow_duration_sec_increase: 1
  upgrade_slow_mult: 100
  upgrade_slow_base: 2
 air:
  range: 4
  cooldown_sec: 10
  flying_target_damage: 10
  non_flying_target_damage: 5
  upgrade_range_increase: 1
  upgrade_range_mult: 100
  upgrade_range_base: 2 
  upgrade_flying_target_damage_increase: 10
  upgrade_non_flying_target_damage_increase: 2
  upgrade_damage_mult: 100
  upgrade_damage_base: 1.5
spells:
 grieta:
  duration_sec: 1
 meteorito:
  damage: 30
  collateral_damage: 10
  collateral_range: 2
 murodefuego:
  damage: 10
  duration_sec: 5
 congelacion:
  duration_sec: 5
 ventisca:
  damage: 10
  duration_sec: 5
  slow_percent: 25
  slow_duration_sec: 2
 tornado:
  max_damage: 50
  duration_sec: 10
 rayos:
  max_damage: 50
units:
 abmonible:
  health_points: 60
  speed: 1
 demonio_verde:
  health_points: 60
  speed: 2
 halcon_sangriento:
  health_points: 60
  speed: 3
 hombre_cabra:
  health_points: 60
  speed: 4
 espectro:
  health_points: 60
  speed: 5
 no_muerto:
  health_points: 60
  speed: 6
