#ifndef TOWERDEFENSE_SPRITENAMESCONFIG_H
#define TOWERDEFENSE_SPRITENAMESCONFIG_H

#define PRADERA 0
#define PRADERA_PATH 1
#define VOLCAN 2
#define VOLCAN_PATH 3
#define GELIDO 4
#define GELIDO_PATH 5
#define DESIERTO 6
#define DESIERTO_PATH 7
#define TIERRAFIRME 8
#define PORTALENTRADA 9
#define PORTALSALIDA 10
#define TORRE_FUEGO 11
#define DISPARO_FUEGO 12
#define TORRE_TIERRA 13
#define DISPARO_TIERRA 14
#define TORRE_AGUA 15
#define DISPARO_AGUA 16
#define TORRE_AIRE 17
#define DISPARO_AIRE 18
#define ABOMINABLE 19
#define FIREWALL 20
#define TOTAL 21

#define AGREGAR_HORDA_BTN 100
#define ENEMIGO_SUMA 101
#define ENEMIGO_RESTA 102
#define ELIMINAR_HORDA_BTN 103
#define FONT 104
#define ABMONIBLE_EDITOR 105
#define TOTAL_EDITOR 106

#endif //TOWERDEFENSE_SPRITENAMESCONFIG_H
