#ifndef TOWERDEFENSE_SPRITENAMESCONFIG_H
#define TOWERDEFENSE_SPRITENAMESCONFIG_H

#define PRADERA 0
#define VOLCAN 3
#define GELIDO 6
#define DESIERTO 9
#define PORTALENTRADA 3
#define PORTALSALIDA 4
#define FIRE_TOWER 5
#define TOTAL 6

#define VOLCAN_EDITOR 100
#define DESIERTO_EDITOR 101
#define GELIDO_EDITOR 102
#define PRADERA_EDITOR 103
#define AGREGAR_HORDA_BTN 104
#define ENEMIGO_SUMA 105
#define ENEMIGO_RESTA 106
#define ELIMINAR_HORDA_BTN 107
#define FONT 108
#define ABMONIBLE_EDITOR 109
#define TOTAL_EDITOR 110

#endif //TOWERDEFENSE_SPRITENAMESCONFIG_H
