#ifndef TOWERDEFENSE_SPRITENAMESCONFIG_H
#define TOWERDEFENSE_SPRITENAMESCONFIG_H

#define PRADERA 0
#define PRADERA_PATH 1
#define VOLCAN 2
#define VOLCAN_PATH 3
#define GELIDO 4
#define GELIDO_PATH 5
#define DESIERTO 6
#define DESIERTO_PATH 7
#define TIERRAFIRME 8
#define PORTALENTRADA 9
#define PORTALSALIDA 10
#define FIRE_TOWER 11
#define DISPARO_FUEGO 12
#define ABOMINABLE 13
#define TOTAL 14

#define AGREGAR_HORDA_BTN 100
#define ENEMIGO_SUMA 101
#define ENEMIGO_RESTA 102
#define ELIMINAR_HORDA_BTN 103
#define FONT 104
#define ABMONIBLE_EDITOR 105
#define TOTAL_EDITOR 106

#endif //TOWERDEFENSE_SPRITENAMESCONFIG_H
