nombre: mapa
superficie: 4
ancho: 10
alto: 13
superficies:
 - x: 1
   y: 3
 - x: 1
   y: 7
 - x: 1
   y: 11
 - x: 5
   y: 1
 - x: 5
   y: 5
 - x: 5
   y: 9
caminos:
 - x: 0
   y: 0
   x_sig: 1
   y_sig: 0
 - x: 1
   y: 0
   x_sig: 2
   y_sig: 0
 - x: 2
   y: 0
   x_sig: 3
   y_sig: 0
 - x: 3
   y: 0
   x_sig: 4
   y_sig: 0
 - x: 4
   y: 0
   x_sig: 5
   y_sig: 0
 - x: 5
   y: 0
   x_sig: 6
   y_sig: 0
 - x: 6
   y: 0
   x_sig: 6
   y_sig: 1
 - x: 6
   y: 1
   x_sig: 6
   y_sig: 2
 - x: 6
   y: 2
   x_sig: 5
   y_sig: 2
 - x: 5
   y: 2
   x_sig: 4
   y_sig: 2
 - x: 4
   y: 2
   x_sig: 3
   y_sig: 2
 - x: 3
   y: 2
   x_sig: 2
   y_sig: 2
 - x: 2
   y: 2
   x_sig: 1
   y_sig: 2
 - x: 1
   y: 2
   x_sig: 0
   y_sig: 2
 - x: 0
   y: 2
   x_sig: 0
   y_sig: 3
 - x: 0
   y: 3
   x_sig: 0
   y_sig: 4
 - x: 0
   y: 4
   x_sig: 1
   y_sig: 4
 - x: 1
   y: 4
   x_sig: 2
   y_sig: 4
 - x: 2
   y: 4
   x_sig: 3
   y_sig: 4
 - x: 3
   y: 4
   x_sig: 4
   y_sig: 4
 - x: 4
   y: 4
   x_sig: 5
   y_sig: 4
 - x: 5
   y: 4
   x_sig: 6
   y_sig: 4
 - x: 6
   y: 4
   x_sig: 6
   y_sig: 5
 - x: 6
   y: 5
   x_sig: 6
   y_sig: 6
 - x: 6
   y: 6
   x_sig: 5
   y_sig: 6
 - x: 5
   y: 6
   x_sig: 4
   y_sig: 6
 - x: 4
   y: 6
   x_sig: 3
   y_sig: 6
 - x: 3
   y: 6
   x_sig: 2
   y_sig: 6
 - x: 2
   y: 6
   x_sig: 1
   y_sig: 6
 - x: 1
   y: 6
   x_sig: 0
   y_sig: 6
 - x: 0
   y: 6
   x_sig: 0
   y_sig: 7
 - x: 0
   y: 7
   x_sig: 0
   y_sig: 8
 - x: 0
   y: 8
   x_sig: 1
   y_sig: 8
 - x: 1
   y: 8
   x_sig: 2
   y_sig: 8
 - x: 2
   y: 8
   x_sig: 3
   y_sig: 8
 - x: 3
   y: 8
   x_sig: 4
   y_sig: 8
 - x: 4
   y: 8
   x_sig: 5
   y_sig: 8
 - x: 5
   y: 8
   x_sig: 6
   y_sig: 8
 - x: 6
   y: 8
   x_sig: 6
   y_sig: 9
 - x: 6
   y: 9
   x_sig: 6
   y_sig: 10
 - x: 6
   y: 10
   x_sig: 5
   y_sig: 10
 - x: 5
   y: 10
   x_sig: 4
   y_sig: 10
 - x: 4
   y: 10
   x_sig: 3
   y_sig: 10
 - x: 3
   y: 10
   x_sig: 2
   y_sig: 10
 - x: 2
   y: 10
   x_sig: 1
   y_sig: 10
 - x: 1
   y: 10
   x_sig: 0
   y_sig: 10
 - x: 0
   y: 10
   x_sig: 0
   y_sig: 11
 - x: 0
   y: 11
   x_sig: 0
   y_sig: 12
 - x: 0
   y: 12
   x_sig: 1
   y_sig: 12
 - x: 1
   y: 12
   x_sig: 2
   y_sig: 12
 - x: 2
   y: 12
   x_sig: 3
   y_sig: 12
 - x: 3
   y: 12
   x_sig: 4
   y_sig: 12
 - x: 4
   y: 12
   x_sig: 5
   y_sig: 12
 - x: 5
   y: 12
   x_sig: 6
   y_sig: 12
 - x: 6
   y: 12
   x_sig: -1
   y_sig: -1
portales:
 - tipo: salida
   x: 6
   y: 12
 - tipo: entrada
   x: 0
   y: 0
hordas:
 - tiempo: 5
   abmonible: 5
   demonio_verde: 0
   espectro: 2
   halcon_sangriento: 0
   hombre_cabra: 0
   no_muerto: 0
 - tiempo: 2
   abmonible: 5
   demonio_verde: 0
   espectro: 0
   halcon_sangriento: 0
   hombre_cabra: 0
   no_muerto: 0
 - tiempo: 2
   abmonible: 5
   demonio_verde: 0
   espectro: 0
   halcon_sangriento: 0
   hombre_cabra: 0
   no_muerto: 0
 - tiempo: 2
   abmonible: 5
   demonio_verde: 0
   espectro: 0
   halcon_sangriento: 0
   hombre_cabra: 0
   no_muerto: 0
