nombre: test
superficie: 0
ancho: 7
alto: 7
superficies: 
 - x: 1
   y: 2
caminos: 
 - x: 0
   y: 1
   x_sig: 1
   y_sig: 1
 - x: 1
   y: 1
   x_sig: 2
   y_sig: 1
 - x: 2
   y: 1
   x_sig: -1
   y_sig: -1
portales: 
 - tipo: entrada
   x: 0
   y: 1
 - tipo: salida
   x: 2
   y: 1
hordas:
 - tiempo: 3
   abmonible: 0
   demonio_verde: 0
   espectro: 0
   halcon_sangriento: 0
   hombre_cabra: 0
   no_muerto: 2
   tiempo_enemigos4
