//
// Created by tino on 12/11/17.
//

#ifndef TOWERDEFENSE_PLAYERJOINEDLOBBYGTKNOTIFICATION_H
#define TOWERDEFENSE_PLAYERJOINEDLOBBYGTKNOTIFICATION_H


class PlayerJoinedLobbyGTKNotification {

};


#endif //TOWERDEFENSE_PLAYERJOINEDLOBBYGTKNOTIFICATION_H
