#ifndef TOWERDEFENSE_MUSICNAMESCONFIG_H
#define TOWERDEFENSE_MUSICNAMESCONFIG_H

#define MAIN_MUSIC_PATH "../Resources/main_music.wav"
#ifndef __CHUNK_ENUM__
#define __CHUNK_ENUM__
enum CHUNK_FILE {
    TOTAL_CHUNKS
} ;
#endif

#endif //TOWERDEFENSE_MUSICNAMESCONFIG_H
