#ifndef TOWERDEFENSE_MUSICNAMESCONFIG_H
#define TOWERDEFENSE_MUSICNAMESCONFIG_H

#define MAIN_MUSIC_PATH "../Resources/main_music.mp3"
#ifndef __CHUNK_ENUM__
#define __CHUNK_ENUM__
enum CHUNK_FILE {
    DISPARO_FUEGO_SONIDO,
    DISPARO_TIERRA_SONIDO,
    DISPARO_AIRE_SONIDO,
    DISPARO_AGUA_SONIDO,
    ENEMIGO_MUERTE_SONIDO,
    TOTAL_CHUNKS
} ;
#endif

#endif //TOWERDEFENSE_MUSICNAMESCONFIG_H
