#ifndef TOWERDEFENSE_CONSTANTS_H
#define TOWERDEFENSE_CONSTANTS_H

#define SUPERFICIE_BUTTON_WIDTH 60
#define SUPERFICIE_BUTTON_HEIGHT 60

#define AGREGAR_CAMINO_BUTTON_X 0
#define AGREGAR_CAMINO_BUTTON_Y 60
#define AGREGAR_CAMINO_BUTTON_WIDTH 60
#define AGREGAR_CAMINO_BUTTON_HEIGHT 60

#define AGREGAR_TIERRA_BUTTON_X 60
#define AGREGAR_TIERRA_BUTTON_Y 60
#define AGREGAR_TIERRA_BUTTON_WIDTH 60
#define AGREGAR_TIERRA_BUTTON_HEIGHT 60

#define AGREGAR_PORTAL_ENTRADA_BUTTON_X 120
#define AGREGAR_PORTAL_ENTRADA_BUTTON_Y 60
#define AGREGAR_PORTAL_ENTRADA_BUTTON_WIDTH 60
#define AGREGAR_PORTAL_ENTRADA_BUTTON_HEIGHT 60

#define AGREGAR_PORTAL_SALIDA_BUTTON_X 180
#define AGREGAR_PORTAL_SALIDA_BUTTON_Y 60
#define AGREGAR_PORTAL_SALIDA_BUTTON_WIDTH 60
#define AGREGAR_PORTAL_SALIDA_BUTTON_HEIGHT 60

#define ALTO_BUTTON_X 0
#define ALTO_BUTTON_Y 120
#define ALTO_BUTTON_WIDTH 40
#define ALTO_BUTTON_HEIGHT 40

#define ALTO_SUMA_BUTTON_X 20
#define ALTO_SUMA_BUTTON_Y 160
#define ALTO_SUMA_BUTTON_WIDTH 20
#define ALTO_SUMA_BUTTON_HEIGHT 20

#define ALTO_RESTA_BUTTON_X 0
#define ALTO_RESTA_BUTTON_Y 160
#define ALTO_RESTA_BUTTON_WIDTH 20
#define ALTO_RESTA_BUTTON_HEIGHT 20

#define ANCHO_BUTTON_X 40
#define ANCHO_BUTTON_Y 120
#define ANCHO_BUTTON_WIDTH 40
#define ANCHO_BUTTON_HEIGHT 40

#define ANCHO_SUMA_BUTTON_X 60
#define ANCHO_SUMA_BUTTON_Y 160
#define ANCHO_SUMA_BUTTON_WIDTH 20
#define ANCHO_SUMA_BUTTON_HEIGHT 20

#define ANCHO_RESTA_BUTTON_X 40
#define ANCHO_RESTA_BUTTON_Y 160
#define ANCHO_RESTA_BUTTON_WIDTH 20
#define ANCHO_RESTA_BUTTON_HEIGHT 20

#define SAVE_BUTTON_X 80
#define SAVE_BUTTON_Y 120
#define SAVE_BUTTON_WIDTH 60
#define SAVE_BUTTON_HEIGHT 60

#define NUEVA_HORDA_BUTTON_X 0
#define NUEVA_HORDA_BUTTON_Y 180
#define NUEVA_HORDA_BUTTON_WIDTH 100
#define NUEVA_HORDA_BUTTON_HEIGHT 25

#define TOTAL_MAIN_BUTTONS 18

#define HORDA_ENEMIGO_PADDING 300
#define HORDA_ENEMIGO_IMG_SIZE 50
#define HORDA_MODIFY_QUANTITY_PADDING HORDA_ENEMIGO_PADDING + HORDA_ENEMIGO_IMG_SIZE
#define HORDA_MODIFY_QUANTITY_SIZE 25
#define HORDA_TOTAL_HEIGHT 100
#define HORDA_QUANTITY_WIDTH 50
#define HORDA_QUANTITY_HEIGHT 28
#define HORDA_QUANTITY_PADDING HORDA_MODIFY_QUANTITY_PADDING + HORDA_MODIFY_QUANTITY_SIZE
#define HORDA_TOTAL_ENEMIES 6
#define HORDA_BUTTONS_PER_ENEMY 4
#define HORDA_TOTAL_BUTTONS HORDA_BUTTONS_PER_ENEMY * (HORDA_TOTAL_ENEMIES + 2) + 2
 //El 2 es por los botones de tiempo
 // El segundo 2 es por el botón de borrar horda y el indicador de numero de
// horda

#define ABMONIBLE_KEY "abmonible"
#define ESPECTRO_KEY "espectro"
#define DEMONIO_VERDE_KEY "demonio_verde"
#define HALCON_SANGRIENTO_KEY "halcon_sangriento"
#define NO_MUERTO_KEY "no_muerto"
#define HOMBRE_CABRA_KEY "hombre_cabra"

#define SCROLL_UP_BUTTON_X 525
#define SCROLL_UP_BUTTON_Y 325
#define SCROLL_UP_BUTTON_WIDTH 50
#define SCROLL_UP_BUTTON_HEIGHT 50

#define SCROLL_DOWN_BUTTON_X 525
#define SCROLL_DOWN_BUTTON_Y 400
#define SCROLL_DOWN_BUTTON_WIDTH 50
#define SCROLL_DOWN_BUTTON_HEIGHT 50

#endif //TOWERDEFENSE_CONSTANTS_H
