#ifndef TOWERDEFENSE_CONSTANTS_H
#define TOWERDEFENSE_CONSTANTS_H

#define SUPERFICIE_BUTTON_X 5
#define SUPERFICIE_BUTTON_Y 35
#define SUPERFICIE_BUTTON_WIDTH 50
#define SUPERFICIE_BUTTON_HEIGHT 50

#define AGREGAR_CAMINO_BUTTON_X 220
#define AGREGAR_CAMINO_BUTTON_Y 35
#define AGREGAR_CAMINO_BUTTON_WIDTH 50
#define AGREGAR_CAMINO_BUTTON_HEIGHT 50

#define AGREGAR_TIERRA_BUTTON_X 272
#define AGREGAR_TIERRA_BUTTON_Y 35
#define AGREGAR_TIERRA_BUTTON_WIDTH 50
#define AGREGAR_TIERRA_BUTTON_HEIGHT 50

#define AGREGAR_PORTAL_ENTRADA_BUTTON_X 325
#define AGREGAR_PORTAL_ENTRADA_BUTTON_Y 35
#define AGREGAR_PORTAL_ENTRADA_BUTTON_WIDTH 50
#define AGREGAR_PORTAL_ENTRADA_BUTTON_HEIGHT 50

#define AGREGAR_PORTAL_SALIDA_BUTTON_X 370
#define AGREGAR_PORTAL_SALIDA_BUTTON_Y 35
#define AGREGAR_PORTAL_SALIDA_BUTTON_WIDTH 50
#define AGREGAR_PORTAL_SALIDA_BUTTON_HEIGHT 50

#define ELIMINAR_TERRENO_BUTTON_X 430
#define ELIMINAR_TERRENO_BUTTON_Y 40
#define ELIMINAR_TERRENO_BUTTON_WIDTH 40
#define ELIMINAR_TERRENO_BUTTON_HEIGHT 40

#define ALTO_SUMA_BUTTON_X 470
#define ALTO_SUMA_BUTTON_Y 40
#define ALTO_SUMA_BUTTON_WIDTH 40
#define ALTO_SUMA_BUTTON_HEIGHT 40

#define ALTO_RESTA_BUTTON_X 510
#define ALTO_RESTA_BUTTON_Y 40
#define ALTO_RESTA_BUTTON_WIDTH 40
#define ALTO_RESTA_BUTTON_HEIGHT 40

#define ANCHO_SUMA_BUTTON_X 550
#define ANCHO_SUMA_BUTTON_Y 40
#define ANCHO_SUMA_BUTTON_WIDTH 40
#define ANCHO_SUMA_BUTTON_HEIGHT 40

#define ANCHO_RESTA_BUTTON_X 590
#define ANCHO_RESTA_BUTTON_Y 40
#define ANCHO_RESTA_BUTTON_WIDTH 40
#define ANCHO_RESTA_BUTTON_HEIGHT 40

#define NUEVA_HORDA_BUTTON_X 50
#define NUEVA_HORDA_BUTTON_Y 153
#define NUEVA_HORDA_BUTTON_WIDTH 355
#define NUEVA_HORDA_BUTTON_HEIGHT 54

#define SAVE_BUTTON_X 96
#define SAVE_BUTTON_Y 0
#define SAVE_BUTTON_WIDTH 48
#define SAVE_BUTTON_HEIGHT 48
#define EXIT_BUTTON_X 48

#define TOTAL_MAIN_BUTTONS 18
#define BUTTONS_PER_HORDA 34

#define HORDA_ENEMIGO_PADDING 90
#define HORDA_ENEMIGO_IMG_SIZE 40
#define HORDA_MODIFY_QUANTITY_PADDING HORDA_ENEMIGO_PADDING + HORDA_ENEMIGO_IMG_SIZE
#define HORDA_MODIFY_QUANTITY_SIZE 20
#define HORDA_TOTAL_HEIGHT 100
#define HORDA_QUANTITY_WIDTH 28
#define HORDA_QUANTITY_HEIGHT 24
#define HORDA_QUANTITY_PADDING HORDA_MODIFY_QUANTITY_PADDING + HORDA_MODIFY_QUANTITY_SIZE
#define HORDA_TOTAL_ENEMIES 6
#define HORDA_BUTTONS_PER_ENEMY 4
#define HORDA_TOTAL_BUTTONS HORDA_BUTTONS_PER_ENEMY * (HORDA_TOTAL_ENEMIES + 2) + 2
 //El 2 es por los botones de tiempo
 // El segundo 2 es por el botón de borrar horda y el indicador de numero de
// horda

#define ABMONIBLE_KEY "abmonible"
#define ESPECTRO_KEY "espectro"
#define DEMONIO_VERDE_KEY "demonio_verde"
#define HALCON_SANGRIENTO_KEY "halcon_sangriento"
#define NO_MUERTO_KEY "no_muerto"
#define HOMBRE_CABRA_KEY "hombre_cabra"

#define SCROLL_UP_BUTTON_X 0
#define SCROLL_UP_BUTTON_Y 128
#define SCROLL_DOWN_BUTTON_X 0
#define SCROLL_DOWN_BUTTON_Y 0
#define SCROLL_BUTTON_SIZE 40

#define BG_BUTTONS_W 200
#define BG_BUTTONS_H 72
#define BG_BUTTONS_DST_W 208
#define BG_BUTTONS_DST_H 92
#define BG_PADDING 5

#define BG_SCROLL_W 410
#define BG_SCROLL_H 508
#define BG_SCROLL_DST_W 455
#define BG_SCROLL_DST_H 128

#define SCROLL_BAR_W 41
#define SCROLL_BAR_H 396
#define SCROLL_BAR_DST_W 40
#define SCROLL_BAR_DST_H 50
#define SCROLL_BAR_Y 40

#define MAX_PADDING 9999

#endif //TOWERDEFENSE_CONSTANTS_H
