#ifndef TOWERDEFENSE_CONSTANTS_H
#define TOWERDEFENSE_CONSTANTS_H

#define SUPERFICIE_BUTTON_WIDTH 50
#define SUPERFICIE_BUTTON_HEIGHT 50

#define AGREGAR_CAMINO_BUTTON_X 0
#define AGREGAR_CAMINO_BUTTON_Y 50
#define AGREGAR_CAMINO_BUTTON_WIDTH 40
#define AGREGAR_CAMINO_BUTTON_HEIGHT 40

#define AGREGAR_TIERRA_BUTTON_X 40
#define AGREGAR_TIERRA_BUTTON_Y 50
#define AGREGAR_TIERRA_BUTTON_WIDTH 40
#define AGREGAR_TIERRA_BUTTON_HEIGHT 40

#define AGREGAR_PORTAL_ENTRADA_BUTTON_X 80
#define AGREGAR_PORTAL_ENTRADA_BUTTON_Y 50
#define AGREGAR_PORTAL_ENTRADA_BUTTON_WIDTH 40
#define AGREGAR_PORTAL_ENTRADA_BUTTON_HEIGHT 40

#define AGREGAR_PORTAL_SALIDA_BUTTON_X 120
#define AGREGAR_PORTAL_SALIDA_BUTTON_Y 50
#define AGREGAR_PORTAL_SALIDA_BUTTON_WIDTH 40
#define AGREGAR_PORTAL_SALIDA_BUTTON_HEIGHT 40

#define ELIMINAR_TERRENO_BUTTON_X 160
#define ELIMINAR_TERRENO_BUTTON_Y 50
#define ELIMINAR_TERRENO_BUTTON_WIDTH 40
#define ELIMINAR_TERRENO_BUTTON_HEIGHT 40

#define NUEVA_HORDA_BUTTON_X 0
#define NUEVA_HORDA_BUTTON_Y 90
#define NUEVA_HORDA_BUTTON_WIDTH 130
#define NUEVA_HORDA_BUTTON_HEIGHT 50

#define ALTO_BUTTON_X 130
#define ALTO_BUTTON_Y 90
#define ALTO_BUTTON_WIDTH 35
#define ALTO_BUTTON_HEIGHT 35

#define ALTO_SUMA_BUTTON_X 148
#define ALTO_SUMA_BUTTON_Y 125
#define ALTO_SUMA_BUTTON_WIDTH 15
#define ALTO_SUMA_BUTTON_HEIGHT 15

#define ALTO_RESTA_BUTTON_X 132
#define ALTO_RESTA_BUTTON_Y 125
#define ALTO_RESTA_BUTTON_WIDTH 15
#define ALTO_RESTA_BUTTON_HEIGHT 15

#define ANCHO_BUTTON_X 165
#define ANCHO_BUTTON_Y 90
#define ANCHO_BUTTON_WIDTH 35
#define ANCHO_BUTTON_HEIGHT 35

#define ANCHO_SUMA_BUTTON_X 183
#define ANCHO_SUMA_BUTTON_Y 125
#define ANCHO_SUMA_BUTTON_WIDTH 15
#define ANCHO_SUMA_BUTTON_HEIGHT 15

#define ANCHO_RESTA_BUTTON_X 167
#define ANCHO_RESTA_BUTTON_Y 125
#define ANCHO_RESTA_BUTTON_WIDTH 15
#define ANCHO_RESTA_BUTTON_HEIGHT 15

#define SAVE_BUTTON_X 0
#define SAVE_BUTTON_Y 140
#define SAVE_BUTTON_WIDTH 200
#define SAVE_BUTTON_HEIGHT 50

#define TOTAL_MAIN_BUTTONS 19

#define HORDA_ENEMIGO_PADDING 200
#define HORDA_ENEMIGO_IMG_SIZE 40
#define HORDA_MODIFY_QUANTITY_PADDING HORDA_ENEMIGO_PADDING + HORDA_ENEMIGO_IMG_SIZE
#define HORDA_MODIFY_QUANTITY_SIZE 20
#define HORDA_TOTAL_HEIGHT 100
#define HORDA_QUANTITY_WIDTH 28
#define HORDA_QUANTITY_HEIGHT 24
#define HORDA_QUANTITY_PADDING HORDA_MODIFY_QUANTITY_PADDING + HORDA_MODIFY_QUANTITY_SIZE
#define HORDA_TOTAL_ENEMIES 6
#define HORDA_BUTTONS_PER_ENEMY 4
#define HORDA_TOTAL_BUTTONS HORDA_BUTTONS_PER_ENEMY * (HORDA_TOTAL_ENEMIES + 2) + 2
 //El 2 es por los botones de tiempo
 // El segundo 2 es por el botón de borrar horda y el indicador de numero de
// horda

#define ABMONIBLE_KEY "abmonible"
#define ESPECTRO_KEY "espectro"
#define DEMONIO_VERDE_KEY "demonio_verde"
#define HALCON_SANGRIENTO_KEY "halcon_sangriento"
#define NO_MUERTO_KEY "no_muerto"
#define HOMBRE_CABRA_KEY "hombre_cabra"

#define SCROLL_UP_BUTTON_X 0
#define SCROLL_UP_BUTTON_Y 200
#define SCROLL_DOWN_BUTTON_X 0
#define SCROLL_DOWN_BUTTON_Y 400
#define SCROLL_BUTTON_SIZE 40

#endif //TOWERDEFENSE_CONSTANTS_H
