#define LOBBY_OPCODE 10
#define CREATE_LOBBY 11
#define GET_LOBBIES 12
#define JOIN_LOBBY 13
#define PLAYER_LEFT_LOBBY 14
#define PLAYER_JOINED_LOBBY 15
#define LEAVE_LOBBY 16

#define LOG_IN	20
#define LOG_IN_FAILED 21
#define LOG_IN_SUCCESS 22

#define NEW_TOWER 30
#define WATER_TOWER 31
#define FIRE_TOWER 32
#define EARTH_TOWER 33
#define AIR_TOWER 34