#define CREATE_LOBBY 11
#define JOIN_LOBBY 13
#define LEAVE_LOBBY 16
#define PLAYER_LEFT_LOBBY 14
#define PLAYER_JOINED_LOBBY 15
#define PLAYER_JOIN 17
#define PLAYER_LEAVE 18
#define PLAYER_IS_READY 19

#define LOG_IN	20
#define LOG_IN_FAILED 21
#define LOG_IN_SUCCESS 22

#define NEW_TOWER 30
#define WATER_TOWER 31
#define FIRE_TOWER 32
#define EARTH_TOWER 33
#define AIR_TOWER 34

#define PLAYER_PICKED_SPELL 40
#define PLAYER_UNPICKED_SPELL 41
#define PICK_SPELL 42
#define UNPICK_SPELL 43

#define GAME_STARTED 44

#ifndef __SPELLS_ENUM__
#define __SPELLS_ENUM__
enum SPELL_TYPE {
    SPELL_TYPE_FIRE,
    SPELL_TYPE_AIR,
    SPELL_TYPE_GROUND,
    SPELL_TYPE_WATER
} ;
#endif