nombre: mapa
superficie: 0
ancho: 7
alto: 7
superficies: 
 - x: 2
   y: 4
 - x: 5
   y: 1
caminos: 
 - x: 0
   y: 6
   x_sig: 1
   y_sig: 6
 - x: 1
   y: 6
   x_sig: 1
   y_sig: 5
 - x: 1
   y: 5
   x_sig: 2
   y_sig: 5
 - x: 2
   y: 5
   x_sig: 3
   y_sig: 5
 - x: 3
   y: 5
   x_sig: 3
   y_sig: 4
 - x: 3
   y: 4
   x_sig: 3
   y_sig: 3
 - x: 3
   y: 3
   x_sig: 2
   y_sig: 3
 - x: 2
   y: 3
   x_sig: 1
   y_sig: 3
 - x: 1
   y: 3
   x_sig: 1
   y_sig: 2
 - x: 1
   y: 2
   x_sig: 1
   y_sig: 1
 - x: 1
   y: 1
   x_sig: 1
   y_sig: 0
 - x: 1
   y: 0
   x_sig: 2
   y_sig: 0
 - x: 2
   y: 0
   x_sig: 3
   y_sig: 0
 - x: 3
   y: 0
   x_sig: 4
   y_sig: 0
 - x: 4
   y: 0
   x_sig: 5
   y_sig: 0
 - x: 5
   y: 0
   x_sig: 6
   y_sig: 0
 - x: 6
   y: 0
   x_sig: 6
   y_sig: 1
 - x: 6
   y: 1
   x_sig: 6
   y_sig: 2
 - x: 6
   y: 2
   x_sig: 6
   y_sig: 3
 - x: 6
   y: 3
   x_sig: 6
   y_sig: 4
 - x: 6
   y: 4
   x_sig: 6
   y_sig: 5
 - x: 6
   y: 5
   x_sig: 6
   y_sig: 6
 - x: 6
   y: 6
   x_sig: -1
   y_sig: -1
portales: 
 - tipo: entrada
   x: 0
   y: 6
 - tipo: salida
   x: 6
   y: 6
hordas:
 - tiempo: 2
   abmonible: 0
   demonio_verde: 0
   espectro: 0
   halcon_sangriento: 0
   hombre_cabra: 5
   no_muerto: 0
   tiempo_hordas: 5
 - tiempo: 2
   abmonible: 0
   demonio_verde: 0
   espectro: 0
   halcon_sangriento: 5
   hombre_cabra: 0
   no_muerto: 0
   tiempo_hordas: 5
 - tiempo: 2
   abmonible: 0
   demonio_verde: 0
   espectro: 0
   halcon_sangriento: 4
   hombre_cabra: 4
   no_muerto: 0
   tiempo_hordas: 5
 - tiempo: 2
   abmonible: 0
   demonio_verde: 0
   espectro: 0
   halcon_sangriento: 6
   hombre_cabra: 6
   no_muerto: 0
   tiempo_hordas: 5
 - tiempo: 1
   abmonible: 0
   demonio_verde: 0
   espectro: 0
   halcon_sangriento: 10
   hombre_cabra: 10
   no_muerto: 0
   tiempo_hordas: 5
