//
// Created by tino on 13/11/17.
//

#ifndef TOWERDEFENSE_UNITCREATEDGAMENOTIFICATION_H
#define TOWERDEFENSE_UNITCREATEDGAMENOTIFICATION_H


class UnitCreatedGameNotification {

};


#endif //TOWERDEFENSE_UNITCREATEDGAMENOTIFICATION_H
