ABOMINABLE:
 WALKING_W: 106
 WALKING_H: 119
 WALKING_START_X: 1765
 WALKING_START_Y: 3537
 WALKING_COLUMNS: 12
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 10
 WALKING_OFFSET_Y: 78
 DYING_W: 201
 DYING_H: 155
 DYING_START_X: 1
 DYING_START_Y: 2273
 DYING_COLUMNS: 18
 DYING_ROWS: 1
 DYING_OFFSET_X: 48
 DYING_OFFSET_Y: 0
DEMONIOVERDE:
 WALKING_W: 130
 WALKING_H: 112
 WALKING_START_X: 1729
 WALKING_START_Y: 3363
 WALKING_COLUMNS: 10
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 30
 WALKING_OFFSET_Y: 70
 DYING_W: 170
 DYING_H: 120
 DYING_START_X: 0
 DYING_START_Y: 1357
 DYING_COLUMNS: 16
 DYING_ROWS: 1
 DYING_OFFSET_X: 18
 DYING_OFFSET_Y: 0
HALCONSANGRIENTO:
 WALKING_W: 99
 WALKING_H: 72
 WALKING_START_X: 1277
 WALKING_START_Y: 1335
 WALKING_COLUMNS: 8
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 20
 WALKING_OFFSET_Y: 80
 DYING_W: 118
 DYING_H: 96
 DYING_START_X: 0
 DYING_START_Y: 12
 DYING_COLUMNS: 23
 DYING_ROWS: 1
 DYING_OFFSET_X: 12
 DYING_OFFSET_Y: 0
ESPECTRO:
 WALKING_W: 222
 WALKING_H: 222
 WALKING_START_X: 1
 WALKING_START_Y: 1777
 WALKING_COLUMNS: 10
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 70
 WALKING_OFFSET_Y: 140
 DYING_W: 222
 DYING_H: 222
 DYING_START_X: 1
 DYING_START_Y: 1
 DYING_COLUMNS: 20
 DYING_ROWS: 1
 DYING_OFFSET_X: 0
 DYING_OFFSET_Y: 0
HOMBRECABRA:
 WALKING_W: 83
 WALKING_H: 80
 WALKING_START_X: 0
 WALKING_START_Y: 0
 WALKING_COLUMNS: 8
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 10
 WALKING_OFFSET_Y: 55
 DYING_W: 161
 DYING_H: 149
 DYING_START_X: 0
 DYING_START_Y: 640
 DYING_COLUMNS: 19
 DYING_ROWS: 1
 DYING_OFFSET_X: 40
 DYING_OFFSET_Y: 30
NOMUERTO:
 WALKING_W: 102
 WALKING_H: 92
 WALKING_START_X: 0
 WALKING_START_Y: 0
 WALKING_COLUMNS: 6
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 15
 WALKING_OFFSET_Y: 50
 DYING_W: 102
 DYING_H: 92
 DYING_START_X: 0
 DYING_START_Y: 736
 DYING_COLUMNS: 15
 DYING_ROWS: 1
 DYING_OFFSET_X: 0
 DYING_OFFSET_Y: 0
DISPARO_FUEGO:
 SHOT_W: 129
 SHOT_H: 129
 SHOT_DST_W: 258
 SHOT_DST_H: 258
 SHOT_FLIGHT_X: 50
 SHOT_FLIGHT_Y: 105
 SHOT_START_X: 0
 SHOT_START_Y: 0
 SHOT_COLUMNS: 16
 SHOT_ROWS: 1
 SHOT_OFFSET_X: 46
 SHOT_OFFSET_Y: 200
 EXPLOSION_W: 129
 EXPLOSION_H: 89
 EXPLOSION_DST_W: 258
 EXPLOSION_DST_H: 178
 EXPLOSION_START_X: 0
 EXPLOSION_START_Y: 169
 EXPLOSION_COLUMNS: 5
 EXPLOSION_ROWS: 1
 EXPLOSION_OFFSET_X: 0
 EXPLOSION_OFFSET_Y: 0
 EXPLOSION_TPS: 100
DISPARO_TIERRA:
 SHOT_W: 47
 SHOT_H: 38
 SHOT_DST_W: 47
 SHOT_DST_H: 38
 SHOT_FLIGHT_X: -54
 SHOT_FLIGHT_Y: -10
 SHOT_START_X: 0
 SHOT_START_Y: 17
 SHOT_COLUMNS: 1
 SHOT_ROWS: 1
 SHOT_OFFSET_X: -50
 SHOT_OFFSET_Y: 80
 EXPLOSION_W: 98
 EXPLOSION_H: 55
 EXPLOSION_DST_W: 98
 EXPLOSION_DST_H: 55
 EXPLOSION_START_X: 0
 EXPLOSION_START_Y: 73
 EXPLOSION_COLUMNS: 11
 EXPLOSION_ROWS: 1
 EXPLOSION_OFFSET_X: 20
 EXPLOSION_OFFSET_Y: 6
 EXPLOSION_TPS: 70
DISPARO_AGUA:
 SHOT_W: 97
 SHOT_H: 97
 SHOT_DST_W: 97
 SHOT_DST_H: 97
 SHOT_FLIGHT_X: -20
 SHOT_FLIGHT_Y: 55
 SHOT_START_X: 0
 SHOT_START_Y: 0
 SHOT_COLUMNS: 14
 SHOT_ROWS: 1
 SHOT_OFFSET_X: -40
 SHOT_OFFSET_Y: 155
 EXPLOSION_W: 160
 EXPLOSION_H: 160
 EXPLOSION_DST_W: 160
 EXPLOSION_DST_H: 160
 EXPLOSION_START_X: 0
 EXPLOSION_START_Y: 97
 EXPLOSION_COLUMNS: 8
 EXPLOSION_ROWS: 1
 EXPLOSION_OFFSET_X: 30
 EXPLOSION_OFFSET_Y: 45
 EXPLOSION_TPS: 100
DISPARO_AIRE:
 SHOT_W: 200
 SHOT_H: 163
 SHOT_DST_W: 200
 SHOT_DST_H: 163
 SHOT_FLIGHT_X: 20
 SHOT_FLIGHT_Y: 60
 SHOT_START_X: 0
 SHOT_START_Y: 2
 SHOT_COLUMNS: 1
 SHOT_ROWS: 1
 SHOT_OFFSET_X: 10
 SHOT_OFFSET_Y: 150
 EXPLOSION_W: 200
 EXPLOSION_H: 165
 EXPLOSION_DST_W: 200
 EXPLOSION_DST_H: 165
 EXPLOSION_START_X: 0
 EXPLOSION_START_Y: 0
 EXPLOSION_COLUMNS: 10
 EXPLOSION_ROWS: 1
 EXPLOSION_OFFSET_X: 0
 EXPLOSION_OFFSET_Y: 2
 EXPLOSION_TPS: 100
TORRE_FUEGO:
 TOWER_W: 63
 TOWER_H: 104
 TOWER_DST_W: 94
 TOWER_DST_H: 156
 TOWER_START_X: 0
 TOWER_START_Y: 0
 TOWER_OFFSET_X: -32
 TOWER_OFFSET_Y: 92
 TOWER_COLUMNS: 1
 TOWER_ROWS: 1
 POWER_W: 23
 POWER_H: 45
 POWER_DST_W: 34
 POWER_DST_H: 67
 POWER_START_X: 0
 POWER_START_Y: 109
 POWER_OFFSET_X: -64
 POWER_OFFSET_Y: 134
 POWER_COLUMNS: 30
 POWER_ROWS: 1
TORRE_TIERRA:
 TOWER_W: 105
 TOWER_H: 128
 TOWER_DST_W: 131
 TOWER_DST_H: 160
 TOWER_START_X: 0
 TOWER_START_Y: 15
 TOWER_OFFSET_X: -12
 TOWER_OFFSET_Y: 86
 TOWER_COLUMNS: 1
 TOWER_ROWS: 1
 POWER_W: 0
 POWER_H: 0
 POWER_DST_W: 0
 POWER_DST_H: 0
 POWER_START_X: 0
 POWER_START_Y: 0
 POWER_OFFSET_X: 0
 POWER_OFFSET_Y: 0
 POWER_COLUMNS: 1
 POWER_ROWS: 1
TORRE_AGUA:
 TOWER_W: 57
 TOWER_H: 116
 TOWER_DST_W: 85
 TOWER_DST_H: 174
 TOWER_START_X: 0
 TOWER_START_Y: 17
 TOWER_OFFSET_X: -34
 TOWER_OFFSET_Y: 110
 TOWER_COLUMNS: 1
 TOWER_ROWS: 1
 POWER_W: 40
 POWER_H: 40
 POWER_DST_W: 60
 POWER_DST_H: 60
 POWER_START_X: 0
 POWER_START_Y: 133
 POWER_OFFSET_X: -44
 POWER_OFFSET_Y: 125
 POWER_COLUMNS: 13
 POWER_ROWS: 1
TORRE_AIRE:
 TOWER_W: 60
 TOWER_H: 100
 TOWER_DST_W: 90
 TOWER_DST_H: 150
 TOWER_START_X: 0
 TOWER_START_Y: 17
 TOWER_OFFSET_X: -32
 TOWER_OFFSET_Y: 90
 TOWER_COLUMNS: 1
 TOWER_ROWS: 1
 POWER_W: 106
 POWER_H: 116
 POWER_DST_W: 106
 POWER_DST_H: 116
 POWER_START_X: 0
 POWER_START_Y: 136
 POWER_OFFSET_X: -30
 POWER_OFFSET_Y: 134
 POWER_COLUMNS: 17
 POWER_ROWS: 1
GRIETA:
 SPELL_W: 202
 SPELL_H: 54
 SPELL_DST_W: 303
 SPELL_DST_H: 76
 SPELL_START_X: 0
 SPELL_START_Y: 4
 SPELL_COLUMNS: 9
 SPELL_ROWS: 1
 SPELL_OFFSET_X: 54
 SPELL_OFFSET_Y: 0
 SPELL_TPS: 60
 SPELL_TANSPARENCY: 255
 SPELL_DISPLAY_MODE: 2
METEORITO:
 SPELL_W: 97
 SPELL_H: 227
 SPELL_DST_W: 194
 SPELL_DST_H: 454
 SPELL_START_X: 1
 SPELL_START_Y: 0
 SPELL_COLUMNS: 15
 SPELL_ROWS: 2
 SPELL_OFFSET_X: 18
 SPELL_OFFSET_Y: 384
 SPELL_TPS: 50
 SPELL_TANSPARENCY: 255
 SPELL_DISPLAY_MODE: 1
FIREWALL:
 SPELL_W: 119
 SPELL_H: 160
 SPELL_DST_W: 119
 SPELL_DST_H: 160
 SPELL_START_X: 1
 SPELL_START_Y: 0
 SPELL_COLUMNS: 20
 SPELL_ROWS: 1
 SPELL_OFFSET_X: -14
 SPELL_OFFSET_Y: 94
 SPELL_TPS: 100
 SPELL_TANSPARENCY: 180
 SPELL_DISPLAY_MODE: 0
CONGELACION:
 SPELL_W: 192
 SPELL_H: 192
 SPELL_DST_W: 192
 SPELL_DST_H: 192
 SPELL_START_X: 0
 SPELL_START_Y: 0
 SPELL_COLUMNS: 5
 SPELL_ROWS: 6
 SPELL_OFFSET_X: 16
 SPELL_OFFSET_Y: 110
 SPELL_TPS: 50
 SPELL_TANSPARENCY: 150
 SPELL_DISPLAY_MODE: 1
VENTISCA:
 SPELL_W: 128
 SPELL_H: 128
 SPELL_DST_W: 160
 SPELL_DST_H: 160
 SPELL_START_X: 0
 SPELL_START_Y: 0
 SPELL_COLUMNS: 56
 SPELL_ROWS: 1
 SPELL_OFFSET_X: 0
 SPELL_OFFSET_Y: 90
 SPELL_TPS: 48
 SPELL_TANSPARENCY: 180
 SPELL_DISPLAY_MODE: 0
TORNADO:
 SPELL_W: 134
 SPELL_H: 134
 SPELL_DST_W: 160
 SPELL_DST_H: 160
 SPELL_START_X: 0
 SPELL_START_Y: 0
 SPELL_COLUMNS: 15
 SPELL_ROWS: 1
 SPELL_OFFSET_X: 6
 SPELL_OFFSET_Y: 90
 SPELL_TPS: 90
 SPELL_TANSPARENCY: 220
 SPELL_DISPLAY_MODE: 0
RAYO:
 SPELL_W: 261
 SPELL_H: 256
 SPELL_DST_W: 130
 SPELL_DST_H: 128
 SPELL_START_X: 6
 SPELL_START_Y: 0
 SPELL_COLUMNS: 15
 SPELL_ROWS: 1
 SPELL_OFFSET_X: -14
 SPELL_OFFSET_Y: 64
 SPELL_TPS: 80
 SPELL_TANSPARENCY: 200
 SPELL_DISPLAY_MODE: 1
PING:
 SPELL_W: 512
 SPELL_H: 560
 SPELL_DST_W: 80
 SPELL_DST_H: 88
 SPELL_START_X: 0
 SPELL_START_Y: 0
 SPELL_COLUMNS: 5
 SPELL_ROWS: 1
 SPELL_OFFSET_X: -39
 SPELL_OFFSET_Y: 52
 SPELL_TPS: 200
 SPELL_TANSPARENCY: 255
 SPELL_DISPLAY_MODE: 0
