ABOMINABLE:
 WALKING_W: 106
 WALKING_H: 119
 WALKING_START_X: 1765
 WALKING_START_Y: 3537
 WALKING_COLUMNS: 12
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 10
 WALKING_OFFSET_Y: 78
 DYING_W: 201
 DYING_H: 155
 DYING_START_X: 1
 DYING_START_Y: 2273
 DYING_COLUMNS: 18
 DYING_ROWS: 1
 DYING_OFFSET_X: 48
 DYING_OFFSET_Y: 0
DEMONIOVERDE:
 WALKING_W: 106
 WALKING_H: 119
 WALKING_START_X: 1765
 WALKING_START_Y: 3537
 WALKING_COLUMNS: 12
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 10
 WALKING_OFFSET_Y: 78
 DYING_W: 201
 DYING_H: 155
 DYING_START_X: 1
 DYING_START_Y: 2273
 DYING_COLUMNS: 18
 DYING_ROWS: 1
 DYING_OFFSET_X: 48
 DYING_OFFSET_Y: 0
HALCONSANGRIENTO:
 WALKING_W: 99
 WALKING_H: 72
 WALKING_START_X: 1277
 WALKING_START_Y: 1335
 WALKING_COLUMNS: 8
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 20
 WALKING_OFFSET_Y: 80
 DYING_W: 118
 DYING_H: 96
 DYING_START_X: 0
 DYING_START_Y: 12
 DYING_COLUMNS: 23
 DYING_ROWS: 1
 DYING_OFFSET_X: 12
 DYING_OFFSET_Y: 0
ESPECTRO:
 WALKING_W: 106
 WALKING_H: 119
 WALKING_START_X: 1765
 WALKING_START_Y: 3537
 WALKING_COLUMNS: 12
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 10
 WALKING_OFFSET_Y: 78
 DYING_W: 201
 DYING_H: 155
 DYING_START_X: 1
 DYING_START_Y: 2273
 DYING_COLUMNS: 18
 DYING_ROWS: 1
 DYING_OFFSET_X: 48
 DYING_OFFSET_Y: 0
HOMBRECABRA:
 WALKING_W: 106
 WALKING_H: 119
 WALKING_START_X: 1765
 WALKING_START_Y: 3537
 WALKING_COLUMNS: 12
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 10
 WALKING_OFFSET_Y: 78
 DYING_W: 201
 DYING_H: 155
 DYING_START_X: 1
 DYING_START_Y: 2273
 DYING_COLUMNS: 18
 DYING_ROWS: 1
 DYING_OFFSET_X: 48
 DYING_OFFSET_Y: 0
NOMUERTO:
 WALKING_W: 106
 WALKING_H: 119
 WALKING_START_X: 1765
 WALKING_START_Y: 3537
 WALKING_COLUMNS: 12
 WALKING_ROWS: 1
 WALKING_OFFSET_X: 10
 WALKING_OFFSET_Y: 78
 DYING_W: 201
 DYING_H: 155
 DYING_START_X: 1
 DYING_START_Y: 2273
 DYING_COLUMNS: 18
 DYING_ROWS: 1
 DYING_OFFSET_X: 48
 DYING_OFFSET_Y: 0