#ifndef TOWERDEFENSE_SPRITENAMESCONFIG_H
#define TOWERDEFENSE_SPRITENAMESCONFIG_H

#define PRADERA 0
#define VOLCAN 3
#define GELIDO 6
#define DESIERTO 9
#define TOTAL 3

#endif //TOWERDEFENSE_SPRITENAMESCONFIG_H
